### ISSUE TITLE
About the reward function and termination condition of o2arcenv

### ISSUE THREAD

**Issue by dlqudwns** [ConfeitoHS/arcle#1] opened 2023-09-23 00:33 UTC
Currently reward is given when env.answer is equal to current self.grid. The environment is not terminated until submit action is executed.

This two will cause the optimal agent to not submit. I believe this is not an intended behavior.

**Comment by ConfeitoHS** [comment] 2023-09-25 03:14
Sorry for the late check. Yes, it is not intended behavior. I am fixing this quickly as possible. This will be resolved on 0.2.2 If the problem has resolved then I will close this issue

**Comment by ConfeitoHS** [comment] 2023-09-25 03:42
Updated 0.2.2. Check the repository and arcle pypi site. If there are further bugs, please open another issue!

**Closed as completed by ConfeitoHS** 2023-09-25 03:42 UTC
